name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v5

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

  build-latex:
    uses: ./.github/workflows/latex-build.yml
    needs: [tagging]
    with:
      working-directory: 'paper'
      tex-file: 'document.tex'

  release-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-latex]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download compiled PDF
        uses: actions/download-artifact@v4
        with:
          name: latex-build-artifact
          path: ${{ needs.build-latex.outputs.pdf_path }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true
          files: ${{ needs.build-latex.outputs.pdf_path }}/*.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.build-latex.outputs.pdf_path }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
